version: "3"
services:
  mosquitto:
    build: .
    restart: always
    env_file: ph-meter.env
    ports:
      - 1883:1883
    networks:
      - phmeter
    volumes:
      - /opt/ph-meter/influxdb:/var/lib/influxdb

  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - 2003:2003
    networks:
      - phmeter

  grafana:
    image: grafana/grafana
    restart: always
    env_file: ph-meter.env
    environment: 
      GF_INSTALL_PLUGINS: grafana-image-renderer
    ports:
      - 3000:3000
    networks:
      - phmeter
    volumes:
      - /opt/ph-meter/grafana:/var/lib/grafana

networks:
  phmeter:
