version: "3"
services:
  mosquitto:
    build: .
    restart: always
    env_file: ph-meter.env
    ports:
      - 1883:1883
    volumes:
      - /opt/ph-meter/influxdb:/var/lib/influxdb

  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - 2003:2003

  grafana:
    image: grafana/grafana
    restart: always
    env_file: ph-meter.env
    ports:
      - 3000:3000
    networks:
      - default
      - traefik
    volumes:
      - /opt/ph-meter/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phmeter.entrypoints=web-secure"
      - "traefik.http.routers.phmeter.rule=Host(`phmeter.svard.me`)"
      - "traefik.http.routers.phmeter.tls=true"
      - "traefik.http.routers.phmeter.tls.certresolver=letsencrypt"
        #- "traefik.http.services.phmeter.loadbalancer.server.port=3000"

  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: always
    ports:
      - 8081

networks:
  traefik:
    external:
      name: traefik
